services:
  - type: web
    name: finance-tracker-api
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        fromDatabase:
          name: finance-tracker-db
          property: connectionString

databases:
  - name: finance-tracker-db
    databaseName: finance_tracker
    plan: free
